### Example GET
GET https://jsonplaceholder.typicode.com/posts/1

### Step 1: Hide a secret message
POST http://localhost:3000/stego
Content-Type: application/json

{
  "mode": "hide",
  "coverText": "This is a sample cover text for steganography. It should be long enough to hide the secret message. Make sure to provide sufficient length to accommodate the hidden data. The quick brown fox jumps over the lazy dog. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
  "secretText": "meet@12",
  "algo": "aes",
  "key": "12@u"
}

### Step 2: Extract the secret message (use the stegoText from Step 1 response)
POST http://localhost:3000/stego
Content-Type: application/json

{
  "mode": "extract",
  "stegoText": "PASTE_THE_STEGOTEXT_FROM_STEP_1_RESPONSE_HERE",
  "algo": "aes",
  "key": "12@u"
}
